#!/usr/bin/env ruby

require 'rubygems'
require 'nokogiri'
require 'reverse_markdown'
require 'date'

path = ARGV[0]
abort 'Usage: ./transblogrify {root_path}' if path.nil?

def read_dir(dir)
  Dir.glob("#{dir}/*").each do |f|
    if File.file?(f)
      m = /musings\/\d+\/\d+\/(.+)\.html/.match(f)
      if m and m[1].match(/index|cid/).nil?
        puts f
        @entries[f] = process(m[0], f)
      end 
    elsif File.directory?(f)
      read_dir(f)
    end
  end
end

def process(shortcut, path)
  src = Nokogiri::HTML(open(path))
  entry = src.css('#beta-inner')
  { 
    :shortcut => shortcut,
    :date => Date.parse(entry.css('.date-header').text), 
    :title => entry.css('.entry-header').text,
    :body =>  ReverseMarkdown.parse(entry.css('.entry-content').first)
  }
end

@entries = {}
read_dir path
puts @entries.count